"""Lista unica de composiciones textiles para el dropdown de Material. La usan atributos.py y generar_html.py."""
MATERIALES = [
    "Algodón 100%",
    "Algodón 95% / Elastano 5%",
    "Algodón 98% / Elastano 2% (mezclilla)",
    "Algodón 80% / Poliéster 20%",
    "Algodón 60% / Poliéster 40%",
    "Poliéster 100%",
    "Poliéster 95% / Elastano 5%",
    "Poliéster 65% / Algodón 35%",
    "Poliéster 70% / Viscosa 30%",
    "Viscosa 100%",
    "Viscosa 95% / Elastano 5%",
    "Lino 100%",
    "Lino 55% / Algodón 45%",
    "Lana 100%",
    "Lana 80% / Poliamida 20%",
    "Seda 100%",
    "Cashmere 100%",
    "Lana 90% / Cashmere 10%",
    "Poliamida (nylon) 100%",
    "Poliamida 80% / Elastano 20%",
    "Acrílico 100%",
    "Poliuretano 100% (piel sintética)",
    "Cuero 100%",
]
